plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ggomzipapa.abcfrog'
    compileSdk 36

    defaultConfig {
        applicationId "com.ggomzipapa.abcfrog"
        minSdk 24
        targetSdk 36
        versionCode 9
        versionName "1.0.9"
    }

    signingConfigs {
        release {
            storeFile file("release-keystore.jks")
            storePassword "abcfrog123"
            keyAlias "abc-frog"
            keyPassword "abcfrog123"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.play:review:2.0.1'
}
